name: stingray-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiobotocore=2.25.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - anyio=4.11.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - astropy=7.1.1
  - astropy-base=7.1.1
  - astropy-iers-data=0.2025.11.3.0.38.37
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.8
  - aws-c-common=0.12.5
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.7
  - aws-c-io=0.23.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.0
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - black=25.1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bokeh=3.8.0
  - botocore=1.40.49
  - bottleneck=1.6.0
  - bqplot=0.12.45
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - dask-core=2025.10.0
  - dask-expr=2.0.0
  - datashader=0.18.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - gast=0.4.0
  - gflags=2.2.2
  - glog=0.7.1
  - h11=0.16.0
  - h2=4.3.0
  - h5py=3.15.1
  - hdf5=1.14.6
  - holoviews=1.21.0
  - hpack=4.1.0
  - html5lib=1.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - hvplot=0.12.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - iniconfig=2.3.0
  - ipydatagrid=1.4.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - jplephem=2.23
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.0
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - llvmlite=0.45.1
  - locket=1.0.0
  - lz4-c=1.10.0
  - markdown=3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - mistune=3.1.4
  - mpmath=1.3.0
  - multidict=6.6.3
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - narwhals=2.10.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - notebook-shim=0.2.4
  - numba=0.62.1
  - numpy=2.3.4
  - openjpeg=2.5.4
  - openssl=3.5.4
  - orc=2.2.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - panel=1.8.2
  - param=2.2.1
  - parso=0.8.5
  - partd=1.4.2
  - pathspec=0.12.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.0.0
  - pip=25.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.5.0
  - pluggy=1.6.0
  - prometheus-cpp=1.3.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py2vega=0.6.1
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pycparser=2.22
  - pyct=0.6.0
  - pyerfa=2.0.1.5
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.11.9
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - re2=2025.11.05
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.28.0
  - s2n=1.6.0
  - s3fs=2025.10.0
  - scipy=1.16.3
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - stack_data=0.6.3
  - stingray=2.2.10
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.3.0
  - toolz=1.1.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.3
  - types-python-dateutil=2.9.0.20251008
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - uncompresspy=0.4.1
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - watchfiles=1.1.1
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wrapt=1.17.3
  - xarray=2025.10.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.10.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - docutils==0.22.3
      - git-filter-repo==2.47.0
prefix: /home/kartikmandar/anaconda3/envs/stingray-env
